In [11]:
#Q1. Student Performance DataFrame: Construction and Analysis
#A college wants to analyze student performance using the following data.

In [12]:
import pandas as pd

In [13]:
data = {
    "student_id":[101,102,103,104,105,106,107,108,109,110,111,112,],
    "name":["amit","priya","rahul","neha","vikas","pooja","karan","Simran", "Arjun", "Meena",
                "Rohit", "Anjali"],
    "age":[19,20,18,21,20,19,22,18,21,20,19,22],
    "hours_studies":[2,5,3,8,6,4,9,2,7,5,6,8,],
    "attendance":[65,85,70,95,88,75,98,60,90,82,86,94],
    "marks":[48,78,55,92,84,67,96,45,89,76,81,93]
}

In [14]:
df=pd.DataFrame(data)

In [15]:
df

    student_id    name  age  hours_studies  attendance  marks
0          101    amit   19              2          65     48
1          102   priya   20              5          85     78
2          103   rahul   18              3          70     55
3          104    neha   21              8          95     92
4          105   vikas   20              6          88     84
5          106   pooja   19              4          75     67
6          107   karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [16]:
print(df.shape)

(12, 6)

In [17]:
print(df.shape[0])  #rows

12

In [18]:
print(df.shape[1])   #colums

6

In [19]:
assert df.shape == (12,6)

In [20]:
print("columns names:" ,df.columns.tolist())  #columns names

columns names: ['student_id', 'name', 'age', 'hours_studies', 'attendance', 'marks']

In [21]:
identifiers =["student_id"]
categorical=["name"]
numerical=["age","hours_studies","attendance","marks"]  #storing coulms as variables

In [22]:
print("identifiers", identifiers)
print("categorical",categorical)
print("numerical",numerical)  #printvairables

identifiers ['student_id']
categorical ['name']
numerical ['age', 'hours_studies', 'attendance', 'marks']

In [23]:
selected=df[["name","marks","hours_studies"]]
selected

      name  marks  hours_studies
0     amit     48              2
1    priya     78              5
2    rahul     55              3
3     neha     92              8
4    vikas     84              6
5    pooja     67              4
6    karan     96              9
7   Simran     45              2
8    Arjun     89              7
9    Meena     76              5
10   Rohit     81              6
11  Anjali     93              8

In [24]:
avg=df["marks"].mean()
print("avg:",avg)   #avg of marks

avg: 75.33333333333333

In [25]:
above_avg=selected[selected["marks"]>avg]
print('data')
print(above_avg)  #finding students marks more than avg=75.3

data
      name  marks  hours_studies
1    priya     78              5
3     neha     92              8
4    vikas     84              6
6    karan     96              9
8    Arjun     89              7
9    Meena     76              5
10   Rohit     81              6
11  Anjali     93              8

In [26]:
print("original filtered indices:",above_avg.index.tolist())

original filtered indices: [1, 3, 4, 6, 8, 9, 10, 11]

In [27]:
reset_df=above_avg.reset_index(drop=True)

In [28]:
df

    student_id    name  age  hours_studies  attendance  marks
0          101    amit   19              2          65     48
1          102   priya   20              5          85     78
2          103   rahul   18              3          70     55
3          104    neha   21              8          95     92
4          105   vikas   20              6          88     84
5          106   pooja   19              4          75     67
6          107   karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [29]:
print(reset_df)

     name  marks  hours_studies
0   priya     78              5
1    neha     92              8
2   vikas     84              6
3   karan     96              9
4   Arjun     89              7
5   Meena     76              5
6   Rohit     81              6
7  Anjali     93              8

In [30]:
print(reset_df.index.tolist())

[0, 1, 2, 3, 4, 5, 6, 7]

In [31]:
#Q2 Q2. Advanced Row and Column Selection Using iloc and loc
#Using the DataFrame created in Q1, perform the following operations.

In [33]:
#Select rows at positions 2 through 7 , #iloc uses integer positions, starting from 0
result=df.iloc[2:8][["name","attendance","marks"]]
print(result)

     name  attendance  marks
2   rahul          70     55
3    neha          95     92
4   vikas          88     84
5   pooja          75     67
6   karan          98     96
7  Simran          60     45

In [ ]:
#Set Student_ID as the index and select IDs 103, 107, 110

In [37]:
df_index=df.copy()  #copy() protects the original DataFrame.
df_index.set_index("student_id",inplace=True)  #set_index() makes student IDs the row labels

result=df_index.loc[[103,107,110]]
print(result)

             name  age  hours_studies  attendance  marks
student_id
103         rahul   18              3          70     55
107         karan   22              9          98     96
110         Meena   20              5          82     76

In [46]:
#Apply three Boolean conditions
result=df[
    (df["hours_studies"] >= 6) &
    (df["attendance"] >= 85) &
    (df["marks"] > 80)

]
#Students following all three conditions will appear in this result.
print(result)

    student_id    name  age  hours_studies  attendance  marks
3          104    neha   21              8          95     92
4          105   vikas   20              6          88     84
6          107   karan   22              9          98     96
8          109   Arjun   21              7          90     89
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [49]:
#Extract the last four rows and last three columns
result=df.iloc[-4:,-3:] #-4: selects the last four rows,
#and -3: selects the last three columns.
print(result)

    hours_studies  attendance  marks
8               7          90     89
9               5          82     76
10              6          86     81
11              8          94     93

In [50]:
#Select students scoring below the median
students_median=df["marks"].median()  #median() calculates the middle value
below_median=df[df["marks"]< students_median].copy()

print("students_median   :",  students_median)
print("below_median   :", below_median)

students_median   : 79.5
below_median   :    student_id    name  age  hours_studies  attendance  marks
0         101    amit   19              2          65     48
1         102   priya   20              5          85     78
2         103   rahul   18              3          70     55
5         106   pooja   19              4          75     67
7         108  Simran   18              2          60     45
9         110   Meena   20              5          82     76

In [51]:
#To preserve student_id as the index:
below_median=(
    df.set_index("student_id")  #set_index(drop=True) creates new indices 0, 1, 2, ...
    .loc[lambda x:x["marks"] < students_median]
)
print(below_median)

              name  age  hours_studies  attendance  marks
student_id
101           amit   19              2          65     48
102          priya   20              5          85     78
103          rahul   18              3          70     55
106          pooja   19              4          75     67
108         Simran   18              2          60     45
110          Meena   20              5          82     76

In [57]:
# Q3. Series vs. DataFrame: Feature Selection and Validation
# A machine learning team wants to predict student marks using study hours and attendance.

# Use the following dataset:
#Created the DataFrame

import pandas as pd
df = pd.DataFrame(
    {    "Student_ID": [201, 202, 203, 204, 205,   206, 207, 208, 209, 210    ],

 "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10    ],
  "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95    ],
 "Sleep_Hours": [  8, 7, 8, 6, 7, 6, 7, 8, 6, 7    ],
  "Marks":  [35, 40, 48, 52, 61, 68, 74, 82, 90, 96    ]})

In [58]:
df

   Student_ID  Hours_Studied  Attendance  Sleep_Hours  Marks
0         201              1          50            8     35
1         202              2          55            7     40
2         203              3          60            8     48
3         204              4          65            6     52
4         205              5          70            7     61
5         206              6          75            6     68
6         207              7          80            7     74
7         208              8          85            8     82
8         209              9          90            6     90
9         210             10          95            7     96

In [59]:
#x-feautres
#y-target

In [64]:
X_single=df[["Hours_Studied"]]
y=df["Marks"]

single=df["Hours_Studied"]
double=df[["Hours_Studied"]]

print(type(single))
print(single.shape)

print(type(double))
print(double.shape)

print("\nX_single  :")
print(X_single)

print("\ny   :")
print(y)

<class 'pandas.core.series.Series'>
(10,)
<class 'pandas.core.frame.DataFrame'>
(10, 1)

X_single  :
   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

y     :
0    35
1    40
2    48
3    52
4    61
5    68
6    74
7    82
8    90
9    96
Name: Marks, dtype: int64

In [67]:
#Select multiple features
x_multi=df[["Hours_Studied", "Attendance", "Sleep_Hours"]] #include three columns

print(x_multi) #print columns
print("shape   :",  x_multi.shape)  #shape of columns size

print("marks included   :",  "marks" in x_multi.columns)
print("Student_ID included:", "Student_ID" in x_multi.columns)

   Hours_Studied  Attendance  Sleep_Hours
0              1          50            8
1              2          55            7
2              3          60            8
3              4          65            6
4              5          70            7
5              6          75            6
6              7          80            7
7              8          85            8
8              9          90            6
9             10          95            7
shape   : (10, 3)
marks included   : False
Student_ID included: False

In [69]:
#Use drop() to create X and y
X = df.drop(columns=["Student_ID", "Marks"])
y = df["Marks"]

print("\nFeature columns:")
print(X.columns.tolist())

assert "Marks" not in X.columns
print("Target column excluded!")

Feature columns:
['Hours_Studied', 'Attendance', 'Sleep_Hours']
Target column excluded!

In [70]:
#Validate the data

print("\nNumber of observations:", X.shape[0])
print("Number of features:", X.shape[1])
print("Target dimensions:", y.ndim)

assert X.shape[0] == len(y)
assert X.shape[1] == 3
assert y.ndim == 1

print("All validations passed!")

Number of observations: 10
Number of features: 3
Target dimensions: 1
All validations passed!

In [1]:
#Q4-the DataFrame and inspect it

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Student_ID": range(401, 421),
    "Name": ["A","B","C","D","E","F","G","H","I","J",
             "K","L","M","N","O","P","Q","R","S","T"],
    "Hours_Studied": [1,2,3,4,5,6,7,8,9,10,2,4,6,8,3,5,7,9,1,10],
    "Attendance": [50,55,60,65,70,75,80,85,90,95,58,67,78,88,62,73,83,92,52,98],
    "Sleep_Hours": [5,6,7,8,6,7,8,5,6,7,8,5,6,7,8,6,7,5,6,8],
    "Final_Marks": [30,38,45,52,60,67,75,83,90,98,40,54,70,87,48,63,78,92,34,96]
})

print(df.head())
print("\nShape:", df.shape)

   Student_ID Name  Hours_Studied  Attendance  Sleep_Hours  Final_Marks
0         401    A              1          50            5           30
1         402    B              2          55            6           38
2         403    C              3          60            7           45
3         404    D              4          65            8           52
4         405    E              5          70            6           60

Shape: (20, 6)

In [4]:
#creating a function to reuse for data.shape ,sum
def inspect_df(data):
  print("rows and columns  :", data.shape)
  print("\nColumn Names:")
  print(data.columns.tolist())
  print("\nData Types  :")
  print(data.dtypes)  #datatypes
  print("\nmissing values  :")
  print(data.isnull().sum())   #no of missing values

inspect_df(df)

rows and columns  : (20, 6)

Column Names:
['Student_ID', 'Name', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Final_Marks']

Data Types  :
Student_ID        int64
Name             object
Hours_Studied     int64
Attendance        int64
Sleep_Hours       int64
Final_Marks       int64
dtype: object

missing values  :
Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Sleep_Hours      0
Final_Marks      0
dtype: int64

In [7]:
X_single = df[["Hours_Studied"]]
X_multi = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]
y = df["Final_Marks"]

print("Single Feature Shape:", X_single.shape)
print("Multi Feature Shape:", X_multi.shape)
print("Target Shape:", y.shape)

Single Feature Shape: (20, 1)
Multi Feature Shape: (20, 3)
Target Shape: (20,)

In [8]:
low_attendance = df[df["Attendance"] < 70]

result = low_attendance[["Name", "Student_ID", "Final_Marks"]]

print(result)

   Name  Student_ID  Final_Marks
0     A         401           30
1     B         402           38
2     C         403           45
3     D         404           52
10    K         411           40
11    L         412           54
14    O         415           48
18    S         419           34

In [9]:
result = low_attendance.set_index("Student_ID")[["Name", "Final_Marks"]]
print(result)

           Name  Final_Marks
Student_ID
401           A           30
402           B           38
403           C           45
404           D           52
411           K           40
412           L           54
415           O           48
419           S           34

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_multi, y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (16, 3)
X_test: (4, 3)
y_train: (16,)
y_test: (4,)

In [11]:
print("Indices overlap:",
      len(set(X_train.index) & set(X_test.index)) > 0)

assert len(set(X_train.index) & set(X_test.index)) == 0
assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)

print("All checks passed!")

Indices overlap: False
All checks passed!